# Generated by Django 3.2.15 on 2022-08-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas_previstas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='slug',
            field=models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único.', max_length=300, unique=True),
        ),
    ]
